#!/usr/bin/env python3
"""Build register-bank-fixed SASS of the fold attention kernels (fa_fold_qk2, fa_fold_pv2) into
ggml/src/ggml-cuda/fattn-fold-sass.h. Same method as u2cubin.py:

  1. cut `namespace fa_fold { ... }` out of ggml/src/ggml-cuda/fattn-gemm.cu
  2. per kernel, compile the cut for sm_60 with the build's flags, every other kernel demoted to a
     __device__ function so the cubin holds that kernel alone
  3. disassemble (CuAssembler), rename registers with bankfix.py over the HFMA2 range (a permutation of
     register names: bit-identical by construction; qk2 capped at 128 registers to keep 2 CTAs/SM),
     reassemble
  4. write the cubins, their kernel names and the source hash as a header

Rerun whenever the fa_fold namespace changes; `facubin.py --check` exits 1 if the header is stale
(tools/gate.sh runs it). GGML_CUDA_FA_SASS=0 turns the SASS path off.
usage: facubin.py [--check]
"""
import hashlib, os, re, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '../../..'))
SRC = os.path.join(ROOT, 'ggml/src/ggml-cuda/fattn-gemm.cu')
OUT = os.path.join(ROOT, 'ggml/src/ggml-cuda/fattn-fold-sass.h')
PY = '/mnt/fast/p100-scratch/venv/bin/python'
ASM = '/mnt/fast/p100-scratch/team/gemm/asm.py'
BANKFIX = os.path.join(HERE, 'bankfix.py')
KERNELS = [('qk2', 'fa_fold_qk2', 128), ('pv2', 'fa_fold_pv2', 255)]
PRELUDE = '''#include <cuda_fp16.h>
#include <cstdint>
#include <cfloat>
#define QK4_0 32
typedef struct { half d; uint8_t qs[QK4_0/2]; } block_q4_0;
#define WARP_SIZE 32
'''


def cut():
    s = open(SRC).read()
    a = s.index('namespace fa_fold {')
    b = s.index('} // namespace fa_fold', a) + len('} // namespace fa_fold')
    return s[a:b]


def only(txt, keep):
    """demote every __global__ kernel except `keep` to an (unused, so not emitted) __device__ function"""
    def sub(m):
        return m.group(0) if m.group(2) == keep else 'static __device__ void ' + m.group(2) + '('
    return re.sub(r'static __global__ void (__launch_bounds__\([^)]*\) )?(\w+)\(', sub, txt)


def main():
    txt = cut()
    h = hashlib.sha1(txt.encode()).hexdigest()[:16]
    if '--check' in sys.argv:
        m = re.search(r'fattn_fold_sass_src_hash\[\] = "(\w+)"', open(OUT).read()) if os.path.exists(OUT) else None
        if not m or m.group(1) != h:
            print(f'fattn-fold-sass.h is stale (source hash {h}): rerun {__file__}')
            sys.exit(1)
        print('fattn-fold-sass.h matches the fa_fold kernels')
        return
    tmp = tempfile.mkdtemp(prefix='facubin-', dir='/mnt/fast/p100-scratch')
    blobs = []
    for tag, kname, cap in KERNELS:
        cu = os.path.join(tmp, f'{tag}.cu')
        open(cu, 'w').write(PRELUDE + only(txt, kname) + f'\nvoid * fa_inst = (void *) &fa_fold::{kname};\n')
        cub = os.path.join(tmp, f'{tag}.cubin')
        subprocess.check_call(['nvcc', '-cubin', '-O3', '-DNDEBUG', '-std=c++17', '-use_fast_math',
                               '-arch=sm_60', '-o', cub, cu])
        asm_in, asm_out = cub[:-6] + '.cuasm', cub[:-6] + '_bf.cuasm'
        subprocess.check_call([PY, ASM, 'dis', cub, asm_in], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        t = open(asm_in).read()
        names = re.findall(r'\.text\.(_Z\w+)', t)
        assert len(set(names)) == 1, f'{tag}: expected one kernel, found {set(names)}'
        name = names[0]
        addrs = [int(m.group(1), 16) for m in re.finditer(r'/\*([0-9a-f]{4})\*/[^\n]*HFMA2', t)]
        lo, hi = min(addrs), max(addrs)
        r = subprocess.run([PY, BANKFIX, asm_in, asm_out, f'{lo:x}', f'{hi:x}', str(cap)], capture_output=True, text=True, check=True)
        print(f'{tag} {name}: HFMA2 0x{lo:x}-0x{hi:x}')
        print('  ' + '\n  '.join(l for l in r.stdout.splitlines() if 'conflicts' in l or 'register count' in l))
        cub_bf = cub[:-6] + '_bf.cubin'
        subprocess.check_call([PY, ASM, 'asm', asm_out, cub_bf], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        blobs.append((tag, name, open(cub_bf, 'rb').read()))

    with open(OUT, 'w') as f:
        f.write('// Generated by p100-handoff/tools/sass-gemm/facubin.py -- do not edit.\n')
        f.write('// fa_fold_qk2 / fa_fold_pv2 compiled alone for sm_60, registers renamed to avoid operand bank\n')
        f.write('// conflicts (bankfix.py: a permutation of names, bit-identical results).\n')
        f.write('#pragma once\n')
        f.write(f'static const char fattn_fold_sass_src_hash[] = "{h}";\n')
        for tag, name, data in blobs:
            f.write(f'static const char fattn_fold_sass_name_{tag}[] = "{name}";\n')
            f.write(f'static const unsigned char fattn_fold_sass_{tag}[{len(data)}] = {{\n')
            for i in range(0, len(data), 24):
                f.write('    ' + ', '.join(f'0x{b:02x}' for b in data[i:i + 24]) + ',\n')
            f.write('};\n')
    print(f'wrote {OUT} (source hash {h})')


if __name__ == '__main__':
    main()
