#!/usr/bin/env python3
"""Build the register-bank-fixed SASS of gemm_fold_kernel_u2 (both instances) into
ggml/src/ggml-cuda/gemm-fold-u2-sass.h.

  1. cut the u2 kernel out of ggml/src/ggml-cuda/gemm-fold.cu (GEMM_FOLD_RASTER .. end of namespace)
  2. compile each instance (PAIR = 0, 1) alone to an sm_60 cubin with the build's flags
  3. disassemble (CuAssembler), rename registers with team/gemm/bankfix.py over the HFMA2 block
     (a permutation of register names: bit-identical by construction), reassemble
  4. write both cubins, their kernel names and the source hash as a header

Rerun whenever the u2 kernel changes. `u2cubin.py --check` exits 1 if the header was built from a
different kernel text (tools/gate.sh runs it). GGML_CUDA_GEMM_FOLD_SASS=0 turns the SASS path off.
usage: u2cubin.py [--check]   (from anywhere; paths are fixed)
"""
import hashlib, os, re, subprocess, sys, tempfile

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..'))
SRC = os.path.join(ROOT, 'ggml/src/ggml-cuda/gemm-fold.cu')
OUT = os.path.join(ROOT, 'ggml/src/ggml-cuda/gemm-fold-u2-sass.h')
PY = '/mnt/fast/p100-scratch/venv/bin/python'
ASM = '/mnt/fast/p100-scratch/team/gemm/asm.py'
BANKFIX = '/mnt/fast/p100-scratch/team/gemm/bankfix.py'


def kernel_text():
    s = open(SRC).read()
    a = s.index('constexpr int GEMM_FOLD_RASTER')
    b = s.index('} // namespace', a)
    return s[a:b]


def main():
    ktxt = kernel_text()
    h = hashlib.sha1(ktxt.encode()).hexdigest()[:16]
    if '--check' in sys.argv:
        m = re.search(r'gemm_fold_u2_sass_src_hash\[\] = "(\w+)"', open(OUT).read()) if os.path.exists(OUT) else None
        if not m or m.group(1) != h:
            print(f'gemm-fold-u2-sass.h is stale (kernel hash {h}): rerun {__file__}')
            sys.exit(1)
        print('gemm-fold-u2-sass.h matches the u2 kernel')
        return
    tmp = tempfile.mkdtemp(prefix='u2cubin-', dir='/mnt/fast/p100-scratch')
    blobs = []
    for pair in (0, 1):
        cu = os.path.join(tmp, f'u2_{pair}.cu')
        open(cu, 'w').write(
            '#include <cuda_fp16.h>\n#include <cstdint>\n'
            'constexpr int BM = 128;\nconstexpr int BN = 128;\nconstexpr int BK2 = 16;\n'
            + ktxt +
            f'\nvoid * u2_instance() {{ return (void *) &gemm_fold_kernel_u2<{"true" if pair else "false"}>; }}\n')
        cub = os.path.join(tmp, f'u2_{pair}.cubin')
        subprocess.check_call(['nvcc', '-cubin', '-O3', '-DNDEBUG', '-std=c++17', '-use_fast_math',
                               '-arch=sm_60', '-o', cub, cu])
        asm_in = cub[:-6] + '.cuasm'
        asm_out = cub[:-6] + '_bf.cuasm'
        subprocess.check_call([PY, ASM, 'dis', cub, asm_in], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        txt = open(asm_in).read()
        name = re.search(r'\.text\.(_Z\w*gemm_fold_kernel_u2\w*)', txt).group(1)
        addrs = [int(m.group(1), 16) for m in re.finditer(r'/\*([0-9a-f]{4})\*/[^\n]*HFMA2', txt)]
        lo, hi = min(addrs), max(addrs)
        r = subprocess.run([PY, BANKFIX, asm_in, asm_out, f'{lo:x}', f'{hi:x}'], capture_output=True, text=True, check=True)
        print(f'PAIR={pair} {name}: HFMA2 0x{lo:x}-0x{hi:x}')
        print('  ' + '\n  '.join(l for l in r.stdout.splitlines() if 'conflicts' in l or 'register count' in l))
        cub_bf = cub[:-6] + '_bf.cubin'
        subprocess.check_call([PY, ASM, 'asm', asm_out, cub_bf], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        blobs.append((name, open(cub_bf, 'rb').read()))

    with open(OUT, 'w') as f:
        f.write('// Generated by p100-handoff/tools/sass-gemm/u2cubin.py -- do not edit.\n')
        f.write('// gemm_fold_kernel_u2<false/true> compiled alone for sm_60, registers renamed to avoid\n')
        f.write('// operand bank conflicts (bankfix.py: a permutation of names, bit-identical results).\n')
        f.write('#pragma once\n#include <cstddef>\n')
        f.write(f'static const char gemm_fold_u2_sass_src_hash[] = "{h}";\n')
        for pair, (name, data) in enumerate(blobs):
            f.write(f'static const char gemm_fold_u2_sass_name_{pair}[] = "{name}";\n')
            f.write(f'static const unsigned char gemm_fold_u2_sass_{pair}[{len(data)}] = {{\n')
            for i in range(0, len(data), 24):
                f.write('    ' + ', '.join(f'0x{b:02x}' for b in data[i:i + 24]) + ',\n')
            f.write('};\n')
    print(f'wrote {OUT} (source hash {h})')


if __name__ == '__main__':
    main()
